# Must be unique in a given SonarQube instance
sonar.projectKey=my-telegram-bot
# This is the name and version displayed in the SonarQube UI
sonar.projectName=Telegram Bot
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# This is the folder containing your source code. "." means the current folder.
sonar.sources=.

# Exclude files you don't want to analyze (like the virtual environment or tests)
sonar.exclusions=venv/**,.github/**
