name: PR Agent

on:
  pull_request:
    types: [labeled] # Тригер ТІЛЬКИ на додавання будь-якого лейбла

jobs:
  pr_agent_job:
    # Запускаємо роботу ТІЛЬКИ якщо щойно доданий лейбл називається 'pr-agent-review' 
    # (і якщо це зробив не бот)
    if: ${{ github.event.label.name == 'pr-agent-review' && github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: PR Agent action step
        uses: qodo-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
